services:
  a1111:
    image: chirvo/services/a1111:latest
    container_name: a1111
    # restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - ./volumes/a1111:/app
      - /tmp/output/a1111:/app/a1111/outputs
      - /mnt/fatboy/chirvo/sd/models:/app/a1111/models
      - /mnt/fatboy/chirvo/sd/embeddings:/app/a1111/embeddings
      - /mnt/fatboy/chirvo/sd/extensions/sd-webui-controlnet/models:/app/a1111/extensions/sd-webui-controlnet/models
    ports:
      - "7860:7860"

  comfyui:
    image: chirvo/services/comfyui:latest
    container_name: comfyui
    # restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - ./volumes/comfyui:/app
      - /mnt/fatboy/chirvo/sd/models/Stable-diffusion:/app/comfyui/models/checkpoints
      - /mnt/fatboy/chirvo/sd/models/VAE:/app/comfyui/models/vae
      - /mnt/fatboy/chirvo/sd/models/VAE-approx:/app/comfyui/models/vae_approx
      - /mnt/fatboy/chirvo/sd/models/Lora:/app/comfyui/models/loras
      - /mnt/fatboy/chirvo/sd/embeddings:/app/comfyui/models/embeddings
      - /tmp/output/comfyui:/app/comfyui/output
    ports:
      - "8188:8188"

  ollama:
    image: chirvo/services/ollama:latest
    container_name: ollama
    # restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - /mnt/fatboy/chirvo/ollama:/root/.ollama
    ports:
      - "11434:11434"

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    # restart: unless-stopped
    volumes:
      - ./volumes/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    extra_hosts:
      - host.docker.internal:host-gateway