services:
  a1111:
    build:
      context: .
      dockerfile: ./dockerfiles/a1111.dockerfile
    ports:
      - "7860:7860"
    devices:
      - '/dev/kfd:/dev/kfd'
      - '/dev/dri:/dev/dri'
    group_add:
      - video
    volumes:
      - ./volumes/a1111:/app/stable-diffusion-webui
      - /tmp/output/a1111:/app/stable-diffusion-webui/outputs

  comfy:
    build:
      context: .
      dockerfile: ./dockerfiles/comfy.dockerfile
    ports:
      - "8188:8188"
    devices:
      - '/dev/kfd:/dev/kfd'
      - '/dev/dri:/dev/dri'
    group_add:
      - video
    volumes:
      - ./volumes/comfy:/app/ComfyUI
      - /home/chirvo/comfy_models:/app/ComfyUI/models
      - /tmp/output/comfy:/app/ComfyUI/output
