services:
  a1111:
    image: ai-docker-containers-a1111
    ports:
      - "7860:7860"
    devices:
      - '/dev/kfd:/dev/kfd'
      - '/dev/dri:/dev/dri'
    group_add:
      - video
    volumes:
      - ./volumes/a1111:/app
      # - /tmp/output/a1111:/app/stable-diffusion-webui/outputs

  comfy:
    image: ai-docker-containers-comfy
    ports:
      - "8188:8188"
    devices:
      - '/dev/kfd:/dev/kfd'
      - '/dev/dri:/dev/dri'
    group_add:
      - video
    volumes:
      - ./volumes/comfy:/app
      # - /home/chirvo/comfy_models:/app/ComfyUI/models
      # - /tmp/output/comfy:/app/ComfyUI/output
