services:
  a1111:
    image: chirvo/ai-docker-containers-base:latest
    command: a1111
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - ./volumes/a1111:/app
      - /tmp/output/a1111:/app/stable-diffusion-webui/outputs
    ports:
      - "7860:7860"

  comfy:
    image: chirvo/ai-docker-containers-base:latest
    command: comfy
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - ./volumes/comfy:/app
      # - /home/chirvo/comfy_models:/app/ComfyUI/models
      # - /tmp/output/comfy:/app/ComfyUI/output
    ports:
      - "8188:8188"
