services:
  a1111:
    image: chirvo/services/a1111:latest
    container_name: a1111
    # restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - /tmp/output/a1111:/app/outputs
      - /mnt/fatboys/chirvo/sd/models:/app/models
      - /mnt/fatboys/chirvo/sd/embeddings:/app/embeddings
      - /mnt/fatboys/chirvo/sd/extensions/sd-webui-controlnet/models:/app/extensions/sd-webui-controlnet/models
    ports:
      - "7860:7860"

  comfyui:
    image: chirvo/services/comfyui:latest
    container_name: comfyui
    # restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - /mnt/fatboys/chirvo/sd/models/Stable-diffusion:/app/models/checkpoints
      - /mnt/fatboys/chirvo/sd/models/VAE:/app/models/vae
      - /mnt/fatboys/chirvo/sd/models/VAE-approx:/app/models/vae_approx
      - /mnt/fatboys/chirvo/sd/models/Lora:/app/models/loras
      - /mnt/fatboys/chirvo/sd/embeddings:/app/models/embeddings
      - /tmp/output/comfyui:/app/output
    ports:
      - "8188:8188"

  tortoise-tts:
    image: chirvo/services/tortoise-tts:latest
    container_name: tortoise-tts
    # restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - /mnt/fatboys/chirvo/tortoise-tts/models:/models
    ports:
      - "8188:8188"

  tts-generation-webui:
    image: chirvo/services/tts-generation-webui
    container_name: tts-generation-webui
    # restart: unless-stopped
    volumes:
      - ./volumes/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    extra_hosts:
      - host.docker.internal:host-gateway

  ollama:
    image: chirvo/services/ollama:latest
    container_name: ollama
    # restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - /mnt/fatboys/chirvo/ollama:/root/.ollama
    ports:
      - "11434:11434"

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    # restart: unless-stopped
    volumes:
      - ./volumes/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    extra_hosts:
      - host.docker.internal:host-gateway
